spring.application.name=hello-spring

spring.datasource.url=jdbc:postgresql://localhost:5432/study
spring.datasource.username=d
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true